- server.js
The pull resolves the following issue: Uluwatu blockUI does not stop when some backend API could not be reached.
> CLOUD-396 nodejs backend sends response when proxy request failed

- app/static/js/controllers/clusterController.js
- app/static/js/controllers/notificationController.js
@biharitomi notification based metadata refreshing on active cluster
> CLOUD-413 refresh metadata (notification triggered)

- app/static/js/controllers/credentialController.js
- app/static/tags/credentialpanel.tag
fixed typo in variable name which caused a ui issue.
@martonsereg or @biharitomi its yours.
> CLOUD-338 fixed cred panel

- app/static/js/controllers/notificationController.js
@keyki or @martonsereg pls check this.
Fixed notification nodecount calculation. The cloudbreak pr needs to merge before this pr.
> CLOUD-445 fixed nodecount in notifications

- app/static/js/controllers/clusterController.js
> CLOUD-445 added default nodecount and template when bp change

- app/static/js/controllers/mainController.js
- app/static/tags/template/awsform.tag
- app/static/tags/template/awslist.tag
@keyki @biharitomi 
UI modifications for https://github.com/sequenceiq/cloudbreak/commit/089a64e6108cc29c63d499742f576092ed28eee4
> CLOUD-432 added ephemeral volume type

- app/static/js/controllers.js
- app/static/js/controllers/blueprintController.js
- app/static/js/controllers/clusterController.js
- app/static/js/controllers/credentialController.js
- app/static/js/controllers/templateController.js
- app/static/js/services.js
- app/static/messages.properties
> Ui error handling

- app/static/js/controllers/usageController.js
- app/static/tags/stack/clusterlistpanel.tag
@doktoric - depends on https://github.com/sequenceiq/cloudbreak/pull/428
> CLOUD-413 enable start/stop on gcc

- app/static/js/controllers/notificationController.js
> CLOUD-420 fix popup based notification handling

- app/static/js/controllers/clusterController.js
> CLOUD-450 fixed blueprint selection

- app/static/js/controllers/clusterController.js
> CLOUD-412 update total items on first load

- app/static/js/controllers/clusterController.js
- app/static/js/controllers/templateController.js
- app/static/tags/stack/clusterform.tag
- app/static/tags/template/awsform.tag
> CLOUD-412 fixed master problems

- app/static/js/controllers/templateController.js
- app/static/tags/stack/clusterform.tag
@martonsereg please check this significant fix
> Fix template selection at cluster creation

- app/static/js/controllers/mainController.js
> CLOUD-451: Remove aws instancetypes which does not support HVM amis

- app/static/tags/stack/clusterform.tag
- app/static/tags/template/awsform.tag
> CLOUD-451 fixed disable

- app/static/js/controllers/accountuserController.js
- app/static/js/services.js
- app/static/partials/dashboard.html
- app/static/tags/accountpanel.tag
@doktoric or @biharitomi 
account details.
depends on https://github.com/sequenceiq/sultans/pull/38
> CLOUD-436 added account details

- app/static/js/controllers/clusterController.js
- app/static/js/services.js
- app/static/tags/stack/clusterform.tag
> CLOUD-442 added onfailure suport

- server.js
@biharitomi 
https://github.com/sequenceiq/sultans/pull/40
> CLOUD-472 added encoded source url for redirection

- app/static/js/services.js
@doktoric or @biharitomi 
in case of validationErrors field does not exists -> cause type error on console.
> CLOUD-474 fixed error check

- app/static/js/services.js
> CLOUD-474 added error data nullcheck

- app/static/js/controllers/clusterController.js
- app/static/tags/stack/clusterform.tag
> CLOUD-478 fixed failure handling

- app/static/js/controllers/credentialController.js
- app/static/tags/accountpanel.tag
- app/static/tags/blueprintpanel.tag
- app/static/tags/credentialpanel.tag
- app/static/tags/eventpanel.tag
- app/static/tags/template/azurelist.tag
- app/static/tags/templatepanel.tag
- app/static/tags/usagepanel.tag
- app/static/tags/userspanel.tag
> CLOUD-448 increation fix and panel width fix

- app/static/js/controllers/clusterController.js
- app/static/js/services.js
- app/static/tags/stack/clusterform.tag
> CLOUD-470 added custom vpc support

- app/static/js/controllers/clusterController.js
- app/static/js/services.js
- app/static/tags/stack/clusterform.tag
@biharitomi pls review
**Notes**
Cluster creation will start with stack validation request. If it fails error message, otherwise stack and cluster creation request will be sent.
Depending on https://github.com/sequenceiq/cloudbreak/pull/480
**Outstanding questions**
* Current validation can be removed? (which is: master groups node count must be 1)
> CLOUD-269: blueprint validation improvement

- app/static/js/controllers/credentialController.js
> CLOUD-489 fixed openstack credential creation

- app/static/js/controllers/clusterController.js
- app/static/js/services.js
Needed if sequenceiq/cloudbreak#490 is merged
> API changes in Cloudbreak on cluster POST

- app/static/js/app.js
- app/static/js/controllers/periscopeController.js
- app/static/tags/stack/clusterform.tag
@oleewere 
Fixed:
- VPC input field related ng-pattern parse errors
- unnecessary log is removed from periscope controller
- block ui configured to be in action for all the periscope requests
> CLOUD-485 fix pattern, blockui issues

- .dockerignore
- Dockerfile
- start-docker.sh
> Docker ulu

- app/static/tags/template/awsform.tag
- app/static/tags/template/awslist.tag
> CLOUD-433 EBS volume param added

- app/static/js/controllers/mainController.js
- app/static/js/controllers/templateController.js
- app/static/tags/template/awsform.tag
> CLOUD-433 fixed encrypt validation

- Dockerfile
- start-docker.sh
> Docker fix bash

- server.js
> CLOUD-522 fixed error handling

- app/static/js/controllers/credentialController.js
- app/static/js/services.js
- app/static/tags/credential/azurelist.tag
> CLOUD-666 azure jks regenerate

- LICENSE
> CLOUD-666 added license file

- app/static/js/controllers/clusterController.js
- app/static/js/services.js
- app/static/tags/stack/clusterform.tag
> CLOUD-536 added consul server nodecount

- app/static/js/controllers/clusterController.js
> CLOUD-536 removed default consul server count

- app/static/js/controllers/clusterController.js
- app/static/js/controllers/mainController.js
- app/static/tags/stack/clusterform.tag
> CLOUD-545 added gateway support

- app/static/js/controllers/notificationController.js
@oleewere ,please take a look!
> CLOUD-557 show error message when error notification is handled

- app/static/tags/stack/activecluster.tag
> CLOUD-534 separated start stop

- app/static/tags/template/gccform.tag
- app/static/tags/template/openstackform.tag
> CLOUD-593 fix order of templates' input groups

- app/static/js/controllers/usageController.js
@martonsereg , please take a look!
> rename 'hostGroup' field that is missing from usages json to instanceGroup

- app/static/js/controllers/usageController.js
@oleewere or @martonsereg , please take a look!
> Summarize running hours of hostgroups that relates to the same stack

- app/static/tags/usagepanel.tag
@schfeca75 , please take a look!
> order stack usage rows by hostgroup name

- app/static/partials/dashboard.html
- app/static/tags/accountpanel.tag
- app/static/tags/userspanel.tag
> CLOUD-644 gathering user details only once

- app/static/tags/template/azurelist.tag
> removed hardcoded username from azure template

- server.js
> CLOUD-649 added /info endpoint

- app/static/tags/stack/clusterform.tag
> CLOUD-712 fixed blueprint parsing in firefox

- app/static/js/controllers/clusterController.js
- app/static/js/services.js
- app/static/tags/stack/activecluster.tag
- app/static/tags/stack/clusterform.tag
> CLOUD-722 added bp validation possibility

- app/static/js/controllers/blueprintController.js
- app/static/tags/blueprint/bplist.tag
> CLOUD-712 blueprint list added

- app/static/tags/blueprint/bplist.tag
> CLOUD-712 fixed tab selection

- app/index.html
- app/static/js/controllers/networkController.js
- app/static/js/services.js
- app/static/messages.properties
- app/static/partials/dashboard.html
- app/static/tags/network/awsnetworkform.tag
- app/static/tags/network/awsnetworklist.tag
- app/static/tags/network/azurenetworkform.tag
- app/static/tags/network/azurenetworklist.tag
- app/static/tags/network/commonnetworkfieldslist.tag
- app/static/tags/network/gcpnetworkform.tag
- app/static/tags/network/gcpnetworklist.tag
- app/static/tags/network/openstacknetworkform.tag
- app/static/tags/network/openstacknetworklist.tag
- app/static/tags/networkpanel.tag
- app/static/tags/stack/activecluster.tag
- app/static/tags/stack/clusterform.tag
- app/static/tags/template/openstackform.tag
- app/static/tags/template/openstacklist.tag
@akanto or @oleewere or @doktoric 
Please take a look!
This pull depends on https://github.com/sequenceiq/cloudbreak/pull/623
> CLOUD-657 create individual resource for managing network settings/configurations

- app/static/tags/stack/activecluster.tag
> CLOUD-764 longname renamed to fqdnname

- server.js
> CLOUD-768 sultans proxy request logging

- app/static/js/controllers/clusterController.js
- app/static/tags/stack/activecluster.tag
- app/static/tags/template/gcclist.tag
> CLOUD-736 fixed consul server default count and network panel

- app/static/js/controllers/clusterController.js
- app/static/js/controllers/periscopeController.js
- app/static/js/services.js
- app/static/messages.properties
- app/static/partials/dashboard.html
- app/static/tags/stack/activecluster.tag
- app/static/tags/stack/clusterform.tag
> COUD-743 added amari repository config to ui

- app/static/js/controllers/periscopeController.js
- app/static/tags/stack/activecluster.tag
@doktoric 
Ambari is now available on port 80
> Ambari port is not 8080 anymore

- app/static/js/controllers/mainController.js
- app/static/messages.properties
- app/static/tags/template/awsform.tag
- app/static/tags/template/azureform.tag
- app/static/tags/template/gccform.tag
- app/static/tags/template/openstackform.tag
UI change for https://github.com/sequenceiq/cloudbreak/pull/648
> support d2 instances

- app/static/js/controllers/periscopeController.js
- app/static/js/services.js
- app/static/tags/periscope/periscope.tag
> CLOUD-705 added periscope history to the ui

- app/static/js/controllers/clusterController.js
> CLOUD-796 solve errors that occurs in browser's console

- server.js
> CLOUD-822 set json limit size for body parser

- app/static/tags/stack/activecluster.tag
> CLOUD-822 fixed event panel

- app/static/messages.properties
- app/static/tags/template/awsform.tag
> spot threshold can be lower than 0.1

- app/static/js/controllers/accountuserController.js
- app/static/tags/userspanel.tag
> CLOUD-776 reinvite support

- app/static/js/controllers/clusterController.js
- app/static/messages.properties
- app/static/tags/stack/activecluster.tag
> CLOUD-797 added sync button

- app/static/tags/stack/activecluster.tag
> CLOUD-844 ability to show ports on the ui

- app/static/tags/stack/clusterform.tag
@matyix or @oleewere please review!
it depends on https://github.com/sequenceiq/cloudbreak/pull/695
> CLOUD-836 support dedicated instances on AWS

- app/static/css/cloudbreak-custom.css
- app/static/tags/blueprint/bplist.tag
> CLOUD-848 row support in blueprint list view

- app/static/js/controllers/clusterController.js
- app/static/tags/stack/clusterform.tag
> CLOUD-846 ability to define the number of disks per storage account

- app/static/js/services.js
- server.js
> CLOUD-845 updated error handling

- app/static/tags/stack/activecluster.tag
> CLOUD-797 updated sync button

- app/static/tags/stack/activecluster.tag
> CLOUD-844 renamed services

- app/static/js/controllers/notificationController.js
@oleewere or @doktoric please review!
Changes:
- updating ambari server ip dinamically by notifications
- refresh metadata only when notification relates to the actually selected cluster ($rootScope.activeCluster)
> CLOUD-865 updating ambari server ip dinamically by notifications

- app/static/js/app.js
@doktoric
note: try before merge it
> CLOUD-869 update stack pattern for block-ui

- app/static/js/controllers/accountuserController.js
- app/static/js/services.js
- app/static/messages.properties
- app/static/tags/userspanel.tag
@doktoric 
depends on https://github.com/sequenceiq/cloudbreak/pull/733
> CLOUD-646 delete user cache on permission update

- app/static/js/controllers/blueprintController.js
- app/static/js/controllers/credentialController.js
- app/static/js/controllers/networkController.js
- app/static/js/controllers/templateController.js
- app/static/tags/blueprintpanel.tag
- app/static/tags/credentialpanel.tag
- app/static/tags/networkpanel.tag
- app/static/tags/templatepanel.tag
> CLOUD-875 added alerts to ui

- app/static/js/services.js
@biharitomi 
depends on https://github.com/sequenceiq/cloudbreak/pull/741
> CLOUD-685 ip assign validation

- app/index.html
- app/static/js/controllers/clusterController.js
- app/static/js/controllers/securityGroupController.js
- app/static/js/services.js
- app/static/messages.properties
- app/static/partials/dashboard.html
- app/static/tags/securitygroup/securitygrouplist.tag
- app/static/tags/securitygrouppanel.tag
- app/static/tags/stack/activecluster.tag
- app/static/tags/stack/clusterform.tag
@keyki or @doktoric please review!
It depends on https://github.com/sequenceiq/cloudbreak/pull/746!
- New panel has been created for security group and rule resources to list resources for now that are generated for every account on the backend side.
- Cluster creation form and list view have been extended with the new resources.
> CLOUD-872 ability to manage(list for now) security groups and rules

- app/static/js/controllers/periscopeController.js
> CLOUD-885 use port 443 instead of 80

- app/static/js/controllers/notificationController.js
> CLOUD-886 do not update node count to 0 (notification)

- app/static/js/controllers/clusterController.js
> CLOUD-892 avoid to sync set active cluster status to the invalid 'SYNC'

- app/static/js/controllers/clusterController.js
- app/static/js/services.js
- app/static/messages.properties
- app/static/tags/stack/clusterform.tag
> CLOUD-882 added failure action to the ui

- app/static/tags/stack/activecluster.tag
> CLOUD-878 stop button fixed

- docs/index.md
- server.js
@martonsereg please review!
Changes:
- prevent caching of proxied get requests
- update readme with browser compatibility and get rid of outdated info
> CLOUD-931 prevent caching of proxied get requests

- app/static/tags/stack/clusterform.tag
> CLOUD-945 remove password validation

- app/static/js/controllers/clusterController.js
- app/static/tags/stack/activecluster.tag
> CLOUD-949 aws cluster with ephemeral volumes can not be stopped

- app/static/tags/stack/activecluster.tag
> CLOUD-960 unnecessary char at the end of error messages

- app/static/tags/stack/activecluster.tag
@doktoric 
depends on: https://github.com/sequenceiq/cloudbreak/pull/818
> CLOUD-907 delete decommissioned instances

- app/static/js/controllers/accountuserController.js
> CLOUD-776 clearing invite field after showing invite success message

- app/static/tags/credentialpanel.tag
> CLOUD-854 fixed create credential label

- app/static/js/app.js
- app/static/js/controllers/clusterController.js
- app/static/messages.properties
- app/static/tags/stack/activecluster.tag
@biharitomi pls depends on https://github.com/sequenceiq/cloudbreak/pull/827
> CLOUD-976 added possibility to change ambari credentials

- app/static/tags/stack/activecluster.tag
> CLOUD-976 hide credential change panel in case of ambari is not available

- app/static/js/controllers/clusterController.js
> use strict comparison when filtering

- app/static/js/controllers/clusterController.js
- package.json
> First patch

- server.js
- start-docker.sh
> CLOUD-41906: use dns for service address resolving

- server.js
> CLOUD-41906: using anonymous function in setTimeout()

- server.js
> CLOUD-41906: address resolving timeout can be set via envvar

- app/static/js/controllers/mainController.js
> CLOUD-43501 added frankfurt

- app/static/tags/stack/activecluster.tag
> CLOUD-44147 word wrap

- app/static/js/controllers/clusterController.js
- app/static/js/services.js
- app/static/messages.properties
- app/static/tags/stack/clusterform.tag
> CLOUD-44310 added filesystem support

- app/static/js/controllers/accountuserController.js
- app/static/tags/accountpanel.tag
- app/static/tags/userspanel.tag
- server.js
@sequenceiq/dev pls merge after this https://github.com/sequenceiq/sultans/pull/61
> CLOUD-44323 added ability to define scopes

- app/static/tags/blueprintpanel.tag
- app/static/tags/credentialpanel.tag
- app/static/tags/templatepanel.tag
> CLOUD-44892 Order resources

- app/static/js/controllers/clusterController.js
- app/static/messages.properties
- app/static/tags/stack/clusterform.tag
> CLOUD-47753 gcs filesystem setup

- app/static/js/controllers/clusterController.js
- app/static/js/controllers/notificationController.js
- app/static/js/services.js
- app/static/messages.properties
- app/static/tags/recipe/recipelist.tag
- app/static/tags/stack/activecluster.tag
- app/static/tags/stack/clusterlistpanel.tag
@martonsereg plz test and review
> Cluster status fix

- app/static/js/directives/usageCharts.js
- format.sh
> Improve format script, no need for specify all files

- app/static/js/controllers/clusterController.js
> BUG-45226 Uluwatu js error when selecting openstack credential

- app/static/js/controllers/securityGroupController.js
- app/static/messages.properties
- app/static/tags/securitygroup/securitygroupform.tag
- app/static/tags/securitygrouppanel.tag
- app/static/tags/stack/clusterform.tag
> CLOUD-45514 added sec group definition

- app/static/js/controllers/securityGroupController.js
> CLOUD-45144: ports validation fix

- app/static/js/controllers/clusterController.js
- app/static/js/controllers/mainController.js
- app/static/tags/stack/clusterform.tag
@bbihari and/or @doktoric plz review
> CLOUD-45605 Default Platform variant on Uluwatu

- app/static/js/controllers/clusterController.js
- app/static/tags/stack/clusterform.tag
> CLOUD-45725 remove hard coded HDP repo

- docs/index.md
> CLOUD-45144 added local dev to readme

- app/static/js/controllers/mainController.js
> CLOUD-45976 introduce V2 D instance types

- app/static/js/controllers/mainController.js
> CLOUD-46099 restore platform variants

- app/static/js/controllers/clusterController.js
- app/static/js/controllers/mainController.js
> CLOUD-45605 Fix variant selector

- app/static/js/controllers/clusterController.js
- app/static/js/controllers/mainController.js
- app/static/js/services.js
- app/static/messages.properties
- app/static/tags/stack/clusterform.tag
> CLOUD-45130 added av zone

- app/static/tags/credential/azurermform.tag
- app/static/tags/credential/azurermlist.tag
> BUG-46300 Do not show credential passwords on the UI

- server.js
@keyki please review, but it depends on https://github.com/sequenceiq/cloudbreak/pull/1067
> CLOUD-46300 eliminate credentail passwords from client side of the UI

- app/static/js/controllers/mainController.js
> CLOUD-46476 Brasil South is duplicated on Uluwatu (Azure)

- app/static/js/controllers/notificationController.js
- app/static/messages.properties
- app/static/tags/stack/activecluster.tag
> CLOUD-47009 added ambari progress

- app/static/messages.properties
> CLOUD-46818 fixed filesystem label

- app/static/tags/stack/clusterform.tag
> CLOUD-46818 removed unused js

- server.js
> CLOUD-46707 fix credential secret field elimination

- server.js
- start-docker.sh
> CLOUD-46866 Sultans internal communication

- app/static/js/controllers/notificationController.js
> CLOUD-47138 Update instance meta data if neccessary

- docs/index.md
> Local development readme update

- server.js
> Use 'uluwatu.sid' for storing session in cookie, clear unused cookie references

- app/static/messages.properties
> CLOUD-47843 Ambari server address typo on the Create Cluster UI

- app/static/js/controllers/clusterController.js
- app/static/js/controllers/mainController.js
- app/static/js/controllers/usageController.js
- app/static/js/services.js
- app/static/tags/stack/activecluster.tag
- app/static/tags/stack/configurecluster.tag
- app/static/tags/stack/configurereview.tag
- app/static/tags/usagepanel.tag
> CLOUD-46697 Refactor platform parameters

- app/static/js/controllers/clusterController.js
> Order securitygroups and templates alphabetically when choosing default values for cluster creation

- app/static/js/controllers/clusterController.js
- app/static/js/controllers/mainController.js
> CLOUD-46697 Refactor platform parameters, fix exceptions

- app/static/js/controllers/mainController.js
@biharitomi it was too early to delete these parameters
> CLOUD-46697 Refactor platform parameters, fix deleted params

- app/static/js/controllers/notificationController.js
> Refresh active cluster metadata when available notification arrives

- app/static/messages.properties
- app/static/tags/stack/activecluster.tag
> Create individual button for terminating an instance

- app/static/tags/stack/activecluster.tag
> CLOUD-47856 fixed up and down scale

- app/static/js/controllers/clusterController.js
- app/static/js/controllers/mainController.js
- app/static/js/controllers/templateController.js
- app/static/js/controllers/usageController.js
- app/static/tags/stack/activecluster.tag
- app/static/tags/stack/configurecluster.tag
- app/static/tags/template/awsform.tag
- app/static/tags/template/awslist.tag
- app/static/tags/template/gcpform.tag
- app/static/tags/template/gcplist.tag
> CLOUD-47850 Refactor disk types

- app/static/js/controllers/mainController.js
> CLOUD-46107 Colorize WAIT_FOR_SYNC status

- app/static/js/controllers/mainController.js
@biharitomi 
releated to https://github.com/sequenceiq/cloudbreak/pull/1136
> CLOUD-48386 add support for gcp us-east region

- app/static/js/controllers/notificationController.js
> CLOUD-48394: Filtering for cluster before push it to rootScope.clusters

- app/static/js/console.UI.js
- app/static/tags/stack/clusterlistpanel.tag
@doktoric plz review, i disable cluster details open during DELETE_IN_PROGRESS
> CLOUD-48453 Cluster Details pane stuck after termination

- Dockerfile
- app/index.html
- app/static/.bowerrc
- app/static/bower.json
- docs/index.md
- package.json
> CLOUD-48790 added bower

- app/static/js/controllers/clusterController.js
- app/static/js/controllers/notificationController.js
- app/static/tags/stack/activecluster.tag
> CLOUD-48144 Make Terminate available for Unused nodes as well

- app/static/tags/network/azurenetworkform.tag
- app/static/tags/network/azurenetworklist.tag
> CLOUD-48918 remove addressprefix

- app/static/js/controllers/securityGroupController.js
- app/static/tags/securitygroup/securitygroupform.tag
> CLOUD-48878 Typo throws script error on 'manage security groups' page

- app/static/js/services.js
> CLOUD-48958 GUI: 'Unknown internal error' message for wrong permission

- app/static/js/controllers/templateController.js
- app/static/tags/template/awsform.tag
- app/static/tags/template/awslist.tag
- app/static/tags/template/azureform.tag
- app/static/tags/template/azurelist.tag
- app/static/tags/template/gcpform.tag
- app/static/tags/template/gcplist.tag
- app/static/tags/template/openstackform.tag
- app/static/tags/template/openstacklist.tag
@akanto volumeType and and instanceType moved
> CLOUD-48916 generic platform entities

- app/static/js/controllers/securityGroupController.js
- app/static/tags/blueprint/bpform.tag
- app/static/tags/credential/awsform.tag
- app/static/tags/credential/gcpform.tag
- app/static/tags/credential/openstackform.tag
- app/static/tags/securitygroup/securitygroupform.tag
@biharitomi fixing sec group default name and name validation patterns at several places, plz check
> CLOUD-49133 GUI: New security group has default name

- app/static/js/controllers/templateController.js
> CLOUD-49029 fix azure cloudplatform parameter at template creation

- app/static/tags/templatepanel.tag
> CLOUD-49029 fix list of azure templates

- app/static/js/controllers/clusterController.js
- app/static/tags/stack/configurehostgroups.tag
- app/static/tags/stack/configuresecuritygroup.tag
> CLOUD-49549 fix cluster creation forms' missing default values for Azure

- app/static/js/controllers/clusterController.js
- app/static/tags/stack/activecluster.tag
> CLOUD-48864 Cloudbreak GUI: Ambari server address lapse

- app/static/tags/stack/configuresecuritygroup.tag
> remove unnecessary debug line

- app/static/js/controllers/clusterController.js
- app/static/js/controllers/notificationController.js
- app/static/messages.properties
- app/static/tags/stack/activecluster.tag
> CLOUD-48952 GUI: 'Services' pane does not refresh automatically

- app/static/js/controllers/securityGroupController.js
- app/static/messages.properties
- app/static/tags/securitygrouppanel.tag
> CLOUD-49758 Manage Security Groups pane warning should be consistent

- app/static/js/controllers/clusterController.js
- app/static/messages.properties
> CLOUD-50248 ambari docker images are base on centos 7.1 from now on

- app/static/js/controllers/clusterController.js
- app/static/js/services.js
> CLOUD-49556 wasb validation

- app/static/messages.properties
> CLOUD-51118 fixed validation message

- app/static/messages.properties
- app/static/tags/stack/configurecluster.tag
> CLOUD-51845 Platform variant is hidden

- app/static/messages.properties
- app/static/tags/topology/openstackform.tag
- app/static/tags/topology/openstacklist.tag
> CLOUD-52010 Remove endpoint field from topology

- app/static/tags/template/openstackform.tag
> CLOUD-51565 Uluwatu: OpenStack 'manage resources' hint color is wrong

- app/static/js/controllers/clusterController.js
- app/static/js/services.js
- app/static/messages.properties
- app/static/tags/stack/configurehostgroups.tag
> CLOUD-51131 configurable stack advisor

- app/static/config/displaynames.json
> CLOUD-51691 Uluwatu: 'Seoul' is missing from AWS regions

- app/static/js/controllers/clusterController.js
- app/static/js/controllers/templateController.js
- app/static/tags/template/awsform.tag
- app/static/tags/template/awslist.tag
> CLOUD-52428 Uluwatu: fix volumeType related ui controls

- app/static/js/controllers/clusterController.js
- app/static/tags/stack/configuresecuritygroup.tag
@bbihari @bbihari 
Due to Ambari issues it is not advised to use the stack advisor when kerberos is enabled.
> CLOUD-51131 never apply config recommendation when kerberos is enabled

- app/static/tags/credential/openstacklist.tag
> CLOUD-52085 DB: Old OpenStack credentials shows wrong parameters

- app/static/tags/template/awsform.tag
> CLOUD-52268 GUI: AWS 'manage resources' 'Spot price' hint color is wrong

- app/static/js/controllers/clusterController.js
- app/static/tags/stack/configurecluster.tag
> CLOUD-52742 Native/Heat disappears from UI

- app/index.html
- app/static/js/app.js
- app/static/js/lib/ini.js
- app/static/messages.properties
- app/static/tags/sssdconfig/sssdconfigform.tag
> CLOUD-52775 Validate SSSD configuration

- app/static/js/app.js
- app/static/js/controllers/sssdConfigController.js
- app/static/tags/sssdconfig/sssdconfigform.tag
> CLOUD-52775 Fix SSSD form validation

- Makefile
> CLOUD-52969 Add makefile to trigger docker image building on dockerhub

- app/static/js/controllers.js
- app/static/js/controllers/clusterController.js
- app/static/js/controllers/credentialController.js
- app/static/js/controllers/networkController.js
- app/static/js/controllers/templateController.js
- app/static/js/controllers/topologyController.js
- app/static/tags/credentialpanel.tag
- app/static/tags/networkpanel.tag
- app/static/tags/stack/ambarirepositoryconfig.tag
- app/static/tags/stack/configurecluster.tag
- app/static/tags/stack/configurehostgroups.tag
- app/static/tags/templatepanel.tag
> Fix platform buttons
